[package]
name = "logical"
version = "0.1.0"
authors = ["Marcos Silveira <bymarkone@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "^0.13.0"
log = "^0.4.8"
