[package]
name = "charts"
version = "0.1.0"
authors = ["Marcos Silveira <bymarkone@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
charts = "0.3.0"
csv = "1.1.3"
